rcparams = {'shale.exp.k': 2, 'shale.exp.num_knots_internal': 4,
            'shale.exp.csvsplinefname': 'data_demo/shale_spline_exp.csv',
            'shale.exp.y0_mean': 50.0, 'shale.exp.dx': 1.0,
            'shale.exp.csvtimefname': 'data_demo/shale_time_exp.csv',
            'shale.lstm.y0_mean': 50.0, 'shale.lstm.d': 0.1, 'shale.lstm.xmax': 80.0,
            'shale.lstm.num_points': 100, 'shale.lstm.xdisc_mean': 20.0,
            'shale.lstm.fnamecsv': 'data_demo/shale_lstm_time.csv',
            'shale.lstm_stage.fnamecsv': 'data_demo/shale_lstm_time_stage.csv',
            'shale.lstm.fnamemodel': 'data_demo/model_lstm_time.h5',
            'shale.lstm_stage.d': 0.05, 'shale.lstm_stage.xmax': 90.0,
            'shale.lstm_stage.xdisc_mean': 40.0, 'shale.lstm_stage.num_points': 75,
            'shale.lstm_stage.fnamenormalizer': 'data_demo/shale_lstm_time_stage_norm',
            'shale.lstm_stage.fnamenmodel': 'data_demo/shale_lstm_time_stage.h5',
            'shale.lstm_stage.fnamentraindata': 'data_demo/shale_lstm_time_stage_train.npy',
            'shale.lstm_stage.fnamenblinddata': 'data_demo/shale_lstm_time_stage_blind.npy',
            'shale.lstm_stage.fnamenpreddata': 'data_demo/shale_lstm_time_stage_pred.npy',
            'shale.lstm_stage.xdisc_mult': 0.15, 'shale.lstm.y0_mult': 0.7,
            'shale.lstm.sequence.fnamemodel': 'data_demo/model_lstm_time_sequence.h5',
            'shale.lstm.sequence.fnamenorm': 'data_demo/norm_lstm_time_sequence.h5',
            'shale.lstm.sequence.win.fnamemodel': 'data_demo/model_lstm_time_sequence_win.h5',
            'shale.lstm.sequence.win.fnamenorm': 'data_demo/norm_lstm_time_sequence_win.h5',
            'shale.lstm.sequence.win.grad.fnamemodel': 'data_demo/model_lstm_time_sequence_win_grad.h5',
            'shale.lstm.sequence.win.grad.fnamenorm': 'data_demo/norm_lstm_time_sequence_win_grad.h5'}
